// Package admin holds the operations behind the hub's admin API: creating
// hosts, minting and rotating their agent tokens, and editing the site and
// provider dimensions.
//
// The logic lives here rather than in the HTTP handlers so it can be tested
// against a real database without an HTTP server, and so the handlers stay
// thin enough to be obviously correct.
package admin

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/trick77/netra/internal/hub/auth"
)

// ErrNotFound is returned when an operation names a row that does not exist.
// It is distinct from a database failure so a handler can answer 404 rather
// than 500.
var ErrNotFound = errors.New("not found")

// ErrInvalid is returned for input the caller can fix, so a handler can
// answer 400 rather than 500.
var ErrInvalid = errors.New("invalid")

// ErrConflict is returned when a write loses to a uniqueness constraint, so a
// handler can answer 409 rather than 500.
var ErrConflict = errors.New("conflict")

// classify turns a Postgres constraint violation into one of the sentinel
// errors above. A duplicate name and a reference to a row that does not exist
// are both operator mistakes with an obvious fix -- answering 500 for them
// says "the hub is broken" when the truth is "try a different name".
//
// Anything else is returned unchanged and reaches the client as a bare 500,
// which is correct: an unexpected database error is not the caller's to fix
// and its text is not theirs to read.
func classify(err error) error {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return err
	}

	switch pgErr.Code {
	case pgUniqueViolation:
		return fmt.Errorf("%w: %s already exists", ErrConflict, describeConstraint(pgErr))
	case pgForeignKeyViolation:
		return fmt.Errorf("%w: %s does not exist", ErrInvalid, describeConstraint(pgErr))
	default:
		return err
	}
}

// Postgres SQLSTATEs. Named rather than inlined because 23505 and 23503 differ
// by one digit and mean opposite things.
const (
	pgUniqueViolation     = "23505"
	pgForeignKeyViolation = "23503"
)

// describeConstraint names what the caller collided with, without leaking the
// SQL. The constraint name is generated by Postgres and is stable enough to
// map, but not friendly enough to show.
func describeConstraint(pgErr *pgconn.PgError) string {
	switch pgErr.ConstraintName {
	case "providers_name_key":
		return "a provider with that name"
	case "sites_provider_id_name_key":
		return "a site with that name for that provider"
	case "hosts_site_id_hostname_key":
		return "a host with that name at that site"
	case "hosts_site_id_fkey", "sites_provider_id_fkey":
		return "the referenced row"
	case "tokens_token_hash_key":
		return "that token"
	default:
		return "that record"
	}
}

// Host is one row of the admin host list.
type Host struct {
	ID       int32
	Hostname string
	// SiteID is nil, never 0, when the host is not assigned to a site.
	SiteID *int32
	// LastSeen is nil when the host has never posted a sample.
	LastSeen *time.Time
}

// Service performs admin operations against the hub database.
type Service struct {
	pool *pgxpool.Pool
}

// NewService builds a Service over the given pool.
func NewService(pool *pgxpool.Pool) *Service {
	return &Service{pool: pool}
}

// CreateHost registers a host and mints its first agent token, returning the
// plaintext token. That plaintext exists only in this return value: it is
// never stored, never logged, and cannot be recovered afterwards. An operator
// who loses it rotates rather than reads.
//
// Both writes share a transaction so a host is never created without a token.
func (s *Service) CreateHost(ctx context.Context, hostname string, siteID *int32) (Host, string, error) {
	hostname = strings.TrimSpace(hostname)
	if hostname == "" {
		return Host{}, "", fmt.Errorf("%w: hostname is required", ErrInvalid)
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return Host{}, "", fmt.Errorf("begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	var id int32
	if err := tx.QueryRow(ctx,
		`INSERT INTO hosts (hostname, site_id) VALUES ($1, $2) RETURNING id`,
		hostname, siteID).Scan(&id); err != nil {
		return Host{}, "", fmt.Errorf("insert host: %w", classify(err))
	}

	plain, hash, err := auth.Mint()
	if err != nil {
		return Host{}, "", fmt.Errorf("mint: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`INSERT INTO tokens (host_id, token_hash) VALUES ($1, $2)`, id, hash); err != nil {
		return Host{}, "", fmt.Errorf("insert token: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return Host{}, "", fmt.Errorf("commit: %w", err)
	}

	return Host{ID: id, Hostname: hostname, SiteID: siteID}, plain, nil
}

// RotateToken mints a replacement token for a host and revokes every previous
// one, returning the new plaintext.
//
// The delete and the insert share a transaction because tokens has no UNIQUE
// constraint on host_id: an insert-only rotation would leave the old token
// live -- silently, since the new one works and nothing looks wrong -- and a
// delete that committed alone would lock the agent out with no replacement.
// Neither half is correct without the other.
func (s *Service) RotateToken(ctx context.Context, hostID int32) (string, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", fmt.Errorf("begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	var exists bool
	if err := tx.QueryRow(ctx,
		`SELECT EXISTS (SELECT 1 FROM hosts WHERE id = $1)`, hostID).Scan(&exists); err != nil {
		return "", fmt.Errorf("check host: %w", err)
	}
	if !exists {
		return "", ErrNotFound
	}

	plain, hash, err := auth.Mint()
	if err != nil {
		return "", fmt.Errorf("mint: %w", err)
	}

	if _, err := tx.Exec(ctx, `DELETE FROM tokens WHERE host_id = $1`, hostID); err != nil {
		return "", fmt.Errorf("revoke old tokens: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`INSERT INTO tokens (host_id, token_hash) VALUES ($1, $2)`, hostID, hash); err != nil {
		return "", fmt.Errorf("insert token: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return "", fmt.Errorf("commit: %w", err)
	}
	return plain, nil
}

// DeleteHost removes a host. Its tokens and samples go with it through the
// ON DELETE CASCADE declared in 0001_init.sql.
func (s *Service) DeleteHost(ctx context.Context, hostID int32) error {
	tag, err := s.pool.Exec(ctx, `DELETE FROM hosts WHERE id = $1`, hostID)
	if err != nil {
		return fmt.Errorf("delete host: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// ListHosts returns every host with its last_seen, ordered by hostname.
//
// It reads host_current rather than a hypertable, per spec 8: the list must
// stay cheap however much history exists behind it.
func (s *Service) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := s.pool.Query(ctx,
		`SELECT h.id, coalesce(h.hostname, ''), h.site_id, c.last_seen
		   FROM hosts h
		   LEFT JOIN host_current c ON c.host_id = h.id
		  ORDER BY h.hostname, h.id`)
	if err != nil {
		return nil, fmt.Errorf("query hosts: %w", err)
	}
	defer rows.Close()

	hosts := []Host{}
	for rows.Next() {
		var h Host
		if err := rows.Scan(&h.ID, &h.Hostname, &h.SiteID, &h.LastSeen); err != nil {
			return nil, fmt.Errorf("scan host: %w", err)
		}
		hosts = append(hosts, h)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate hosts: %w", err)
	}
	return hosts, nil
}
